# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder

WORKDIR /app

# Install dependencies and build
COPY package.json tsconfig.json ./
COPY src ./src
COPY resources ./resources
RUN npm install
RUN npm run build
# Remove devDependencies
RUN npm prune --production

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy production files
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/build ./build
COPY --from=builder /app/resources ./resources

ENV NODE_ENV=production

# Run the MCP server
CMD ["node", "build/index.js"]
